import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./embla.css"
import Footer from "@/components/_footer";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Satika",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       
        {
          children
        }
      <Footer />
      </body>
    </html>
  );
}
